export const routes = {
    SPLASH: 'SplashScreen',
    ONBOARD: 'OnboardScreen',
    AUTH_NAV: 'AuthNavScreen',
    AUTH: 'AuthScreen',
    REGISTER: 'FirstRegisterScreen',
    USER_REGISTER: 'UserRegisterScreen',
    VERIFY_CODE: 'VerifyCodeScreen',
    NAVIGATION: 'NavigationScreen',
    CATEGORY: 'CategoryScreen',
    NUMBERS: 'NumbersScreen',
    INPUT_NUMBERS: 'InputNumbersScreen',
    FATE_CARDS: 'FateCardsScreen',
    LUCKY_NUMBERS: 'LuckyNumbersScreen',
    PROFILE: 'ProfileScreen',
    EDIT_PROFILE: 'EditProfileScreen',
    NOTIFICATIONS: 'NotificationsScreen',
}
