export const routes = {
    SPLASH: 'SplashScreen',
    ONBOARD: 'OnboardScreen',
    AUTH_NAV: 'AuthNavScreen',
    AUTH: 'AuthScreen',
    REGISTER: 'FirstRegisterScreen',
    USER_REGISTER: 'UserRegisterScreen',
    VERIFY_CODE: 'VerifyCodeScreen',
    NAVIGATION: 'NavigationScreen',
    MATRIX: 'MatrixScreen',
    PROFILE: 'ProfileScreen',
    NUMEROLOGY_HEALTH: '',
    FATE_CARDS: 'FateCardsScreen',
    PROFESSIONS: '',
    WEAKNESSES: '',
    LUCKY_NUMBERS: 'LuckyNumbersScreen',
    PLANETS: 'PlanetsScreen',
    ANCESTORS: '',
}
